apiVersion: v1
kind: Service
metadata:
  name: {{ include "rapp-simulation.name" . }}
  labels:
    {{- include "rapp-simulation.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8082"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    {{- include "rapp-simulation.selectorLabels" . | nindent 4 }}
